# Generated by Django 4.2.9 on 2024-01-27 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments_created', to='ckbapp.educator'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='educators',
            field=models.ManyToManyField(blank=True, related_name='tournaments_managed', to='ckbapp.educator'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='tournaments_participated', to='ckbapp.student'),
        ),
    ]
