# Generated by Django 4.2.9 on 2024-01-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0013_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_team', to='ckbapp.team'),
        ),
    ]
