# Generated by Django 4.2.9 on 2024-01-31 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0016_repositories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Repositories',
            new_name='Repository',
        ),
    ]
