# Generated by Django 4.2.9 on 2024-02-01 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0018_battle_evaluated'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='maintainability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='reliability',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='battle',
            name='security',
            field=models.BooleanField(default=False),
        ),
    ]
