# Generated by Django 4.2.9 on 2024-02-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0019_battle_maintainability_battle_reliability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='automated_evaluated',
            field=models.BooleanField(default=False),
        ),
    ]
