# Generated by Django 4.2.9 on 2024-02-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0020_battle_automated_evaluated'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_message', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('commit_url', models.URLField()),
                ('pushed_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
