# Generated by Django 4.2.9 on 2024-02-03 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0022_alter_pushedcode_commit_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushedCode',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='automated_evaluated',
        ),
    ]
