# Generated by Django 4.2.9 on 2024-01-25 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maxStudentsForTeam', models.IntegerField()),
                ('registrationDeadline', models.DateField()),
                ('submissionDeadline', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registrationDeadline', models.DateField()),
                ('endingDate', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Educator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ckbapp.user')),
            ],
            bases=('ckbapp.user',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ckbapp.user')),
            ],
            bases=('ckbapp.user',),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('numTeammates', models.IntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckbapp.battle')),
                ('members', models.ManyToManyField(related_name='teams_joined', to='ckbapp.student')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='teams',
            field=models.ManyToManyField(related_name='battles_participated', to='ckbapp.team'),
        ),
        migrations.AddField(
            model_name='battle',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='ckbapp.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='educators',
            field=models.ManyToManyField(related_name='tournaments_managed', to='ckbapp.educator'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='students',
            field=models.ManyToManyField(related_name='tournaments_participated', to='ckbapp.student'),
        ),
        migrations.AddField(
            model_name='battle',
            name='educators',
            field=models.ManyToManyField(related_name='battles_managed', to='ckbapp.educator'),
        ),
    ]
