# Generated by Django 4.2.9 on 2024-01-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='educators',
            field=models.ManyToManyField(blank=True, related_name='tournaments_managed', to='ckbapp.educator'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='tournaments_participated', to='ckbapp.student'),
        ),
    ]
