# Generated by Django 4.2.9 on 2024-01-28 09:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0002_tournament_creator_alter_tournament_educators_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='educators',
        ),
        migrations.AddField(
            model_name='battle',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='battle_created', to='ckbapp.educator'),
        ),
        migrations.CreateModel(
            name='TournamentLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckbapp.student')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='ckbapp.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckbapp.student')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='ckbapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='BattleLeaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='ckbapp.battle')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ckbapp.student')),
            ],
        ),
    ]
