# Generated by Django 4.2.9 on 2024-01-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0003_remove_battle_educators_battle_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='codeKata',
            field=models.FileField(blank=True, upload_to='code_katas/'),
        ),
    ]
