# Generated by Django 4.2.9 on 2024-01-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0008_alter_battle_codekata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battleleaderboard',
            name='battle',
        ),
        migrations.RemoveField(
            model_name='teamleaderboard',
            name='student',
        ),
        migrations.RemoveField(
            model_name='tournamentleaderboard',
            name='tournament',
        ),
        migrations.AddField(
            model_name='battle',
            name='leaderboard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle_leaderboard', to='ckbapp.battleleaderboard'),
        ),
        migrations.AddField(
            model_name='battle',
            name='team_leaderboard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_leaderboard', to='ckbapp.teamleaderboard'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='leaderboard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard', to='ckbapp.tournamentleaderboard'),
        ),
    ]
