# Generated by Django 4.2.9 on 2024-01-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0009_remove_battleleaderboard_battle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='leaderboard',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='team_leaderboard',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='leaderboard',
        ),
        migrations.AddField(
            model_name='battleleaderboard',
            name='battle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='battle_leaderboard', to='ckbapp.battle'),
        ),
        migrations.AddField(
            model_name='teamleaderboard',
            name='battle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='team_leaderboard', to='ckbapp.battle'),
        ),
        migrations.AddField(
            model_name='tournamentleaderboard',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tournament_leaderboard', to='ckbapp.tournament'),
        ),
    ]
