# Generated by Django 4.2.9 on 2024-01-28 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0010_remove_battle_leaderboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battleleaderboard',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battle_leaderboard', to='ckbapp.battle'),
        ),
        migrations.AlterField(
            model_name='teamleaderboard',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_leaderboard', to='ckbapp.battle'),
        ),
        migrations.AlterField(
            model_name='tournamentleaderboard',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_leaderboard', to='ckbapp.tournament'),
        ),
    ]
