# Generated by Django 4.2.9 on 2024-01-29 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0011_alter_battleleaderboard_battle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams_participated', to='ckbapp.battle'),
        ),
    ]
