# Generated by Django 4.2.9 on 2024-01-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0014_invite_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='has_started',
            field=models.BooleanField(default=False),
        ),
    ]
