# Generated by Django 4.2.9 on 2024-02-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ckbapp', '0021_pushedcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushedcode',
            name='commit_message',
            field=models.TextField(null=True),
        ),
    ]
